server:
  port: 8083
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5544/crunchd_order
    pool:
      max-create-connection-time: 5s
      max-size: 10
      initial-size: 5
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5544/crunchd_order
crunch:
  catalog-service-uri: "http://localhost:9001"